otlob/config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :items
  resources :orders
  resources :groups
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  root 'welcome#index'
  mount ActionCable.server => '/cable'

  # AJAX Routes
  post '/users/find', to: 'users#find'
  post '/groups/addToGroup', to: 'groups#addToGroup'
  delete '/groups/removeFromGroup', to: 'groups#removeFromGroup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
   
 
end

otlob/app/models/order.rb
class Order < ApplicationRecord
	has_many :items
	after_create_commit { BroadcastMessageJob.perform_later self }
	belongs_to :user

	has_attached_file :menu, styles: { large:"500x500>", medium: "300x300#", thumb: "100x100#" }
  	validates_attachment_content_type :menu, content_type: /\Aimage\/.*\z/
end

otlob/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.mtype=params[:mtype]
    @order.user_id=current_user.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update 
    if @order.user_id == current_user.id
          respond_to do |format|
          if @order.update(order_params)
            format.html { redirect_to @order, notice: 'Order was successfully updated.' }
            format.json { render :show, status: :ok, location: @order }
          else
            format.html { render :edit }
            format.json { render json: @order.errors, status: :unprocessable_entity }
          end
        end
    else 
      if user_signed_in?
        redirect_to order_path(),
          notice: "Only Owner Who Can Edit The Order"
      else 
        redirect_to new_user_session_path
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    if @order.user_id == current_user.id
      @order.destroy
      respond_to do |format|
        format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
        format.json { head :no_content }
      end
    else 
       if user_signed_in?
        redirect_to order_path(),
          notice: "Only Owner Who Can Delete The Order"
      else 
        redirect_to new_user_session_path
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:menu, :mtype, :restaurant, :user_id)
    end
end

otlob/app/helpers/orders_helper.rb
module OrdersHelper
end

otlob/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :menu %><br>
    <%= form.file_field :menu %>
  </div>

  <div class="field">
    <%= form.label :'Order For' %><br />
    <input name="mtype" value="0" type="radio"> BreakFast<br/>
    <input name="mtype" value="1" type="radio"> Lunch <br/>
  </div>

  <div class="field">
    <%= form.label :'From' %><br />
    <%= form.text_field :restaurant, id: :order_restaurant %>
  </div>
  <div class="field" style="display: none">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :order_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

otlob/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

otlob/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Restaurant</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>  <% if order.mtype == 0 %>
                <p>BreakFast</p>
              <% else %>
                <p>Lunch</p>
              <% end %>
        </td>
        <td><%= order.restaurant %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %> | </td>
        <td><%= link_to 'Edit', edit_order_path(order) %> | </td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

otlob/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

otlob/app/views/orders/show.html.erb
<p>
  <strong>Order For: </strong>
  <% if @order.mtype == 0 %>
  	BreakFast
  <% else %>
  	Lunch
  <% end %>
</p>
  <strong>From Restaurant: </strong>
  <%= @order.restaurant %>
<p>
  <strong>Ordered By: </strong>
  <%= User.find(@order.user_id).name %>
</p>

<%= link_to 'Delete', order_path(@order),method: :delete,data:{confirm:'Are you sure you would like to delete the order?'}%> |
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>