otlob/config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :items
  resources :orders
  resources :groups
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  root 'welcome#index'
  mount ActionCable.server => '/cable'

  # AJAX Routes
  post '/users/find', to: 'users#find'
  post '/groups/addToGroup', to: 'groups#addToGroup'
  delete '/groups/removeFromGroup', to: 'groups#removeFromGroup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
   
 
end

otlob/app/models/group.rb
class Group < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	belongs_to :user
	has_and_belongs_to_many :users
end

otlob/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @group = Group.new
    @users = User.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @users = User.all
    # @data = { group: @group, users: @users }
    # p @data
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    # group_params[:user] = User.find(current_user.id)
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        @group.users.push(current_user)

        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :index }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  #= Function to Add friend To Group from Add Friend form
  def addToGroup
    @friend = User.where(email: params[:fmail]).take
    @group = Group.find(params[:group])
    @res = Hash.new
    if @friend.present?
      if !check_if_friend(@friend.id)
        @res = { error: true, message: "You are not friend to "+@friend.email+" to add to Group" }
      elsif check_in_group(@group,@friend)
        @res = { error: true, message: @friend.name+" is already a member in the Group" }
      else
        @added = @group.users.push(@friend)
        if @added
          @res = { error: false, message: @friend.name+" added to "+@group.name+" group" }
        else
          @res = { error: true, message: "Unable to add "+@friend.email+" to "+@group.name+" group" }
        end
      end
    else
      @res = {error: true, message: params[:fmail]+" doesn't exist"}
    end
    render json: @res
  end

  #= Function to Remove friend from Group
  def removeFromGroup
    p params
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name,:user)
    end


    def check_if_friend(friend_id)
      @friendship = Friendship.where(user_id: current_user.id, friend_id: friend_id).take
      if @friendship.present?
        return true
      else
        return false
      end
    end

    def check_in_group(group,friend)
      for user in group.users
        if user.id == friend.id
          return true
        end
      end
      return false
    end
end

otlob/app/helpers/groups_helper.rb
module GroupsHelper
end

otlob/app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :group_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

otlob/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

otlob/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<%= render 'form', group: @group %>

<fieldset>
  <legend>Your Groups</legend>
  <ul>
    <% for grp in current_user.groups %>
      <div class="btn-group">
        <button class="shGroup btn btn-primary" data="<%= grp.id %>"><%= grp.name %></button>
        <button class="shGroup glyphicon glyphicon-plus" data="<%= grp.id %>"></button>
        <% if current_user.id==grp.user_id %>
          <%= link_to '', group_path(grp), method: :delete, data: { confirm: 'Are you sure?' },
         :class => "glyphicon glyphicon-minus"  %>
        <% end %>
      </div>
      
    <% end %>
  </ul>
</fieldset>

<fieldset>
  <legend>Group</legend>
  <form id="addFriendToGroup">
    <label for="fmail">Your friend email:</label>
    <input type="email" name="fmail" required="required">
    <input type="hidden" name="group" id="curGrp">
    <input type="submit" value="Add" name="add">
  </form>
  <div id="grp">
  </div>
</fieldset>


<br>

otlob/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

otlob/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>User:</strong>
  <% for user in @group.users %>
  <li><%= user.name %></li>
  <% end %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>