otlob/config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :items
  resources :orders
  resources :groups
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  root 'welcome#index'
  mount ActionCable.server => '/cable'

  # AJAX Routes
  post '/users/find', to: 'users#find'
  post '/groups/addToGroup', to: 'groups#addToGroup'
  delete '/groups/removeFromGroup', to: 'groups#removeFromGroup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
   
 
end

otlob/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otlob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
  <div class="nav-left">
    <ul>
      <li><%= link_to 'Home', root_url %></li>  |
      <li><%= link_to 'Friends', friendships_url %></li> |
      <li><%= link_to 'Groups', groups_url %></li>  |
      <li><%= link_to 'Orders', orders_url %></li>
    </ul>
  </div>
  
  <div class="nav-right">
    <% if !current_user.nil? %>
      <%= image_tag current_user.avatar.url(:thumb) %>
      <%= current_user.name %>
      <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
    <% else %>
      <%= link_to "Log in", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>
  </nav>

    <%= yield %>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>